<?php
/* @var $this Mage_Core_Block_Template */
$_helper = $this->helper('aoe_classpathcache'); /* @var $_helper Aoe_ClassPathCache_Helper_Data */
?>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $_helper->getAdminUrl() ?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush Aoe_ClassPathCache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <strong><?php echo Mage::helper('adminhtml')->__('Storage:') ?></strong>
            <?php if(Varien_Autoload::isApcUsed()): ?>
                 <?php echo Mage::helper('adminhtml')->__('APC'); ?>
             <?php elseif(Varien_Autoload::isXcacheUsed()): ?>
                 <?php echo Mage::helper('adminhtml')->__('XCache'); ?>
             <?php else: ?>
                 <?php echo Mage::helper('adminhtml')->__('file') ?>,
             <?php endif; ?>
            <strong><?php echo Mage::helper('adminhtml')->__('Number of entries:') ?></strong>
            <?php echo count(Varien_Autoload::getCache()) ?>
        </td>
    </tr>
</table>